[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[font]
size = 11.0

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[window]
 padding = {x = 0, y = 0}
 # decorations = "Transparent"
 opacity = 0.8
 dynamic_padding = true

[bell]
animation = "Ease"

[cursor]
style = { shape = "Block", blinking = "On" }

[env]
term = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = [ '-c', 'tmux a -t x1 || tmux new-session -s "x1"']

[colors]
# Other Window Background Colors
transparent_background_colors = false

# Default colors
primary.background = "#000000"
primary.foreground = "#e6e6e6"

# Normal colors
# [colors.normal]
# black = "#1c1c1c"
# red = "#ffb3ba"
# green = "#baffc9"
# yellow = "#ffffba"
# blue = "#bae1ff"
# magenta = "#e0e0e0"
# cyan = "#c8c8c8"
# white = "#e6e6e6"

# Bright colors
# [colors.bright]
# black = "#3a3a3a"
# red = "#ffc6cd"
# green = "#d1ffd8"
# yellow = "#ffffd1"
# blue = "#d1e9ff"
# magenta = "#ebebeb"
# cyan = "#d8d8d8"
# white = "#ffffff"

# Dim colors
# [colors.dim]
# black = "#121212"
# red = "#ffa0aa"
# green = "#a3ffb8"
# yellow = "#ffffa3"
# blue = "#a3d4ff"
# magenta = "#d5d5d5"
# cyan = "#b8b8b8"
# white = "#c0c0c0"

[terminal]
