# yazi.toml
[manager]
show_hidden = true
image_quality = 90

[opener]
edit = [
	{ run = 'hx "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
]
